### ISSUE TITLE
In ios14.4 system, on the car's central screen does not display snowflakes

### ISSUE THREAD

**Issue by grzhai** [ryannair05/Snoverlay-2#7]
In ios12, when connected to carplay, the snoverlay plugin displays snowflakes on the car's central screen
In ios14.4 system, the central control screen does not display snowflakes, please help

**Comment by ryannair05** [comment]
Fixed in version 1.0.1

**Comment by grzhai** [comment]
In apple 8 and ios14.4 system, snowflakes still do not appear on the central control screen after carplay is connected. Please help to solve the problem, thank you
